version: '3.6'

services:
  proxy:
    image: traefik:1.7.6
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ../config/traefik.toml:/etc/traefik/traefik.toml:ro
      - ../config/acme.json:/acme.json
    networks:
      default:
        aliases:
          - https://trade.c4ei.net
          - peatio.c4ei.net
          - ws.ranger.c4ei.net
          - superset.c4ei.net
          - eth.c4ei.net
          - tower.c4ei.net
          - monitor.c4ei.net
    labels:
      traefik.enable: true
      traefik.frontend.rule: 'Host: monitor.c4ei.net'
      traefik.port: 8080
